{
  G.sys.lblExit = 'scrExit';
  G.sys.lblStart = 'sysStart';
  const dlgHide: CodeInst[] = [{ dialogFade: { visible: 0, duration: 200 } }, { dialogClear: {} }];
  const dlgShow: CodeInst[] = [{ dialogClear: {} }, { dialogFade: { visible: 1, duration: 200 } }];
  G.specialScripts[(G.sys.sysScript = '_system')] = [
    // on exit
    G.sys.lblExit,
    { dialog: { text: '游戏结束，回到启动画面' } },
    ...dlgHide,
    { jump: { label: G.sys.lblStart } },
    // system start
    G.sys.lblStart,
    { varSet: { idx: 100, val: 128 } },
    { yuri: { action: 1 } },
    { bgColor: { bgr: [0, 0, 0] } },
    { crossfade: { duration: 200 } },
    { jump: { label: 'startMenu' } },
    'igStart', // play ig start
    ...dlgHide,
    { bgColor: { bgr: [0, 0, 0] } },
    { crossfade: { duration: 1 } },
    { bg_0f: { filename: '../system/LOGO1.bmp' } },
    { crossfade: { duration: 5000 } },
    { waitTime: { duration: 1000 } },
    { bg_0f: { filename: '../system/LOGO2.bmp' } },
    { crossfade: { duration: 5000 } },
    { waitTime: { duration: 1000 } },
    { bg_0f: { filename: '../system/CAUTION01.bmp' } },
    { crossfade: { duration: 5000 } },
    { waitTime: { duration: 1000 } },
    { bgColor: { bgr: [0, 0, 0] } },
    { crossfade: { duration: 5000 } },
    { jump: { label: 'startMenu' } },
    'startMenu',
    ...dlgShow,
    { dialog: { text: '游戏已启动，现在你可以加载存档或新开始游戏' } },
    { selBeg: {} },
    { selAdd: { text: '开始游戏', label: 'startGame' } },
    { selAdd: { text: 'IG启动画面', label: 'igStart' } },
    { selAdd: { text: '播放视频', label: 'startMenuVideo' } },
    { selEnd: {} },
    'startGame',
    ...dlgHide,
    { jumpScript: { filename: 'start.s' } },
    'startMenuVideo',
    ...dlgHide,
    { selBeg: {} },
    { selAdd: { text: '返回启动菜单', label: 'startMenu' } },
    { selAdd: { text: '播放OP视频', label: 'opVideo' } },
    { selAdd: { text: '(冬篇)播放OP2', label: 'hiverOp2' } },
    { selAdd: { text: '(冬篇)播放GrandFinale', label: 'hiverGF' } },
    { selAdd: { text: '测试调查(冬篇)', label: 'testInv' } },
    { selEnd: {} },
    'opVideo',
    { video: { kind: 0 } },
    { jump: { label: 'startMenu' } },
    'hiverOp2',
    { video: { kind: 2 } },
    { jump: { label: 'startMenu' } },
    'hiverGF',
    { video: { kind: 1 } },
    { jump: { label: 'startMenu' } },
    'testInv',
    { "bg_0f": { "layer": 1, "filename": "cut08c.bmp" } },
    { "crossfade": { "duration": 1000 } },
    { "dialog": { "text": "私が気付いた、この二人の共通点は二つ――" }, "__afterString": [0, 60, 130, 179] },
    { "varSet": { "idx": 103, "val": 0 } },
    { "varSet": { "idx": 104, "val": 0 } },
    { "zeroInvItemTimes": {} },
    { "startInvestigate": { "idx": 1 } },
  ];
}
